# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e02a60adb4272d994021ca63e89fa5b5976f1f1a8018472787eac67af45ecca8b236abc2ed5ef4bef55a4b7c1d974f68888533bd058ee8d5fd74a4af999ec6

test:
  secret_key_base: c7d298b5d0421dcfe98e3e19d81150c5e45605798c712b2e932128c15ca9e178a90416bb8f454e889a728969156c07a92db5f1553590ecd1006499ff193c6859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
